import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ActionIcon, AppShell, Avatar, Badge, Burger, Button, Card, Center, ColorSwatch,
  Divider, Group, Loader, MantineProvider, Modal, NumberInput, Paper, ScrollArea,
  SegmentedControl, Select, SimpleGrid, Stack, Table, Text, TextInput, ThemeIcon,
  Title, Tooltip, createTheme,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { DonutChart } from '@mantine/charts';
import { Notifications, notifications } from '@mantine/notifications';
import {
  LayoutDashboard, ArrowLeftRight, Shapes, WalletCards, Plus, Search, Bell,
  ArrowDownLeft, ArrowUpRight, Utensils, Car, ShoppingBag, House, HeartPulse,
  Gamepad2, Gift, Ellipsis, Wallet, Sparkles, TrendingUp, CirclePlus, Trash2,
  Pencil, Building2, Smartphone, CreditCard, CalendarDays, ChevronRight,
  MoreHorizontal, ReceiptText,
} from 'lucide-react';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/notifications/styles.css';
import './styles.css';
import { api } from './api';

const theme=createTheme({primaryColor:'indigo',colors:{indigo:['#eef1ff','#dfe5ff','#bdc9ff','#94a7ff','#6c84f6','#4c68ed','#3154e5','#2845c8','#243ba0','#23357e']},fontFamily:'Pretendard, "Noto Sans SC", sans-serif',headings:{fontFamily:'Pretendard, "Noto Sans SC", sans-serif',fontWeight:'700'},defaultRadius:'md'});
const money=v=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',minimumFractionDigits:2}).format(Number(v||0));
const iconMap={Utensils,Car,ShoppingBag,House,HeartPulse,Gamepad2,Gift,Ellipsis,Wallet,Sparkles,TrendingUp,CirclePlus};
const nav=[['dashboard','总览',LayoutDashboard],['transactions','日常收支',ArrowLeftRight],['categories','收支分类',Shapes],['accounts','资金账户',WalletCards]];
const emptySummary={totalBalance:0,monthIncome:0,monthExpense:0,monthBalance:0,transactionCount:0,expenseByCategory:[],recentTransactions:[]};

function App(){
  const [page,setPage]=useState('dashboard'),[mobileOpen,mobile]=useDisclosure(false),[recordOpen,recordModal]=useDisclosure(false);
  const [loading,setLoading]=useState(true),[summary,setSummary]=useState(emptySummary),[accounts,setAccounts]=useState([]),[categories,setCategories]=useState([]),[transactions,setTransactions]=useState([]);
  const refresh=useCallback(async()=>{setLoading(true);try{const [s,a,c,t]=await Promise.all([api.dashboard(),api.accounts(),api.categories(),api.transactions()]);setSummary(s);setAccounts(a);setCategories(c);setTransactions(t.records)}catch(e){notifications.show({color:'red',title:'加载失败',message:e.message})}finally{setLoading(false)}},[]);
  useEffect(()=>{refresh()},[refresh]);
  const go=id=>{setPage(id);mobile.close()};
  return <MantineProvider theme={theme}><Notifications position="top-right"/><AppShell header={{height:70}} navbar={{width:220,breakpoint:'sm',collapsed:{mobile:!mobileOpen}}} padding={0}>
    <AppShell.Header className="topbar"><Group h="100%" px={{base:16,sm:26}} justify="space-between"><Group><Burger opened={mobileOpen} onClick={mobile.toggle} hiddenFrom="sm" size="sm"/><Text fw={700} hiddenFrom="sm">Cost Count</Text></Group><Group><TextInput className="top-search" placeholder="搜索账目" leftSection={<Search size={15}/>} w={220}/><ActionIcon variant="default" radius="xl" size="lg"><Bell size={17}/></ActionIcon><Avatar color="indigo" radius="xl">Z</Avatar></Group></Group></AppShell.Header>
    <AppShell.Navbar className="sidebar" p="md"><Stack h="100%" gap={0}><Group className="logo"><Center>¥</Center><div><Text fw={800}>Cost Count</Text><Text size="9px" c="dimmed">PERSONAL LEDGER</Text></div></Group><Text className="menu-title">我的财务</Text><Stack gap={5}>{nav.map(([id,label,Icon])=><button className={`nav-link ${page===id?'active':''}`} key={id} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span>{id==='transactions'&&<Badge size="xs" variant="light">{summary.transactionCount}</Badge>}</button>)}</Stack><Paper className="quick-note" p="md" radius="lg" mt="auto"><ThemeIcon color="yellow" variant="light" radius="xl"><Sparkles size={16}/></ThemeIcon><Text fw={700} size="sm" mt="sm">本月结余 {money(summary.monthBalance)}</Text><Text size="xs" c="dimmed" mt={3}>保持记录，月底就不会再猜钱花去哪了。</Text></Paper><Group className="user-row" pt="md" mt="md"><Avatar size="sm" color="gray">Z</Avatar><div className="grow"><Text size="xs" fw={600}>我的账本</Text><Text size="10px" c="dimmed">本地个人使用</Text></div><MoreHorizontal size={16}/></Group></Stack></AppShell.Navbar>
    <AppShell.Main className="main"><div className="content">{loading?<Center h={480}><Loader/></Center>:<>
      {page==='dashboard'&&<Dashboard summary={summary} accounts={accounts} onAdd={recordModal.open} go={go}/>} 
      {page==='transactions'&&<TransactionsPage data={transactions} categories={categories} accounts={accounts} onAdd={recordModal.open} onRefresh={refresh}/>} 
      {page==='categories'&&<CategoriesPage data={categories} onRefresh={refresh}/>} 
      {page==='accounts'&&<AccountsPage data={accounts} onRefresh={refresh}/>} 
    </>}</div></AppShell.Main>
    <RecordModal opened={recordOpen} onClose={recordModal.close} accounts={accounts} categories={categories} onSaved={async()=>{recordModal.close();await refresh()}}/>
  </AppShell></MantineProvider>;
}

function PageHead({kicker,title,text,action}){return <Group className="page-head" justify="space-between" align="flex-end"><div><Text className="kicker">{kicker}</Text><Title order={1}>{title}</Title><Text size="sm" c="dimmed" mt={6}>{text}</Text></div>{action}</Group>}
function SectionHead({title,sub,action}){return <Group justify="space-between" mb="lg"><Group gap="xs"><Title order={3}>{title}</Title><Text size="xs" c="dimmed">{sub}</Text></Group>{action&&<Button variant="subtle" size="xs" rightSection={<ChevronRight size={14}/>}>{action}</Button>}</Group>}

function Dashboard({summary,accounts,onAdd,go}){
  const donut=summary.expenseByCategory.map(x=>({name:x.categoryName,value:Number(x.amount),color:x.color}));
  return <div className="page-in"><PageHead kicker="AUGUST 21, FRIDAY" title="今天也记得清清楚楚。" text="日常收支、分类和账户余额都在这里。" action={<Button leftSection={<Plus size={16}/>} onClick={onAdd}>记一笔</Button>}/><div className="hero-grid"><Paper className="balance-card" p={28} radius="xl"><Text size="sm" c="dimmed">全部可用资金</Text><Title order={2} mt={8}>{money(summary.totalBalance)}</Title><SimpleGrid cols={2} mt={34}><div className="mini-stat"><Text size="xs" c="dimmed">本月收入</Text><Text fw={700} c="teal" mt={4}>+ {money(summary.monthIncome)}</Text></div><div className="mini-stat"><Text size="xs" c="dimmed">本月支出</Text><Text fw={700} c="red" mt={4}>− {money(summary.monthExpense)}</Text></div></SimpleGrid><Button variant="subtle" mt="lg" px={0} onClick={()=>go('accounts')}>管理 {accounts.length} 个账户 <ChevronRight size={14}/></Button></Paper><Paper className="month-balance" p={28} radius="xl"><Group justify="space-between"><ThemeIcon size={44} radius="xl" variant="light" color={summary.monthBalance>=0?'teal':'red'}>{summary.monthBalance>=0?<TrendingUp size={20}/>:<ArrowUpRight size={20}/>}</ThemeIcon><Badge variant="light" color="gray">本月 {summary.transactionCount} 笔</Badge></Group><Text size="sm" c="dimmed" mt="xl">本月净结余</Text><Title order={2} mt={5} c={summary.monthBalance>=0?'teal':'red'}>{summary.monthBalance>=0?'+ ':''}{money(summary.monthBalance)}</Title><Text size="xs" c="dimmed" mt={8}>收入减去支出后的余额</Text></Paper><Paper className="category-card" p={24} radius="xl"><SectionHead title="支出去向" sub="本月"/><Group justify="space-around" className="donut-wrap">{donut.length?<DonutChart size={150} thickness={18} data={donut}/>:<Center h={150}><Text c="dimmed" size="sm">还没有支出</Text></Center>}<Stack gap={9} className="donut-list">{summary.expenseByCategory.slice(0,5).map(x=><Group justify="space-between" wrap="nowrap" key={x.categoryName}><Group gap={7}><ColorSwatch color={x.color} size={9}/><Text size="xs">{x.categoryName}</Text></Group><Text size="xs" fw={600}>{money(x.amount)}</Text></Group>)}</Stack></Group></Paper></div><Paper className="section" p={24} radius="xl" mt="lg"><SectionHead title="最近账目" sub="按交易日期排序" action="查看全部"/><TransactionTable data={summary.recentTransactions}/></Paper></div>;
}

function TransactionsPage({data,categories,accounts,onAdd,onRefresh}){
  const [type,setType]=useState('ALL'),[keyword,setKeyword]=useState('');
  const filtered=data.filter(x=>(type==='ALL'||x.type===type)&&(!keyword||`${x.merchant}${x.note||''}`.includes(keyword)));
  const remove=async id=>{try{await api.deleteTransaction(id);notifications.show({color:'teal',message:'账目已删除，账户余额已恢复'});await onRefresh()}catch(e){notifications.show({color:'red',message:e.message})}};
  return <div className="page-in"><PageHead kicker="DAILY RECORDS" title="日常收支" text="先把最常用的每一笔记下来，再慢慢分析。" action={<Button leftSection={<Plus size={16}/>} onClick={onAdd}>记一笔</Button>}/><Paper className="section" p={20} radius="xl"><Group justify="space-between"><SegmentedControl value={type} onChange={setType} data={[{label:'全部',value:'ALL'},{label:'支出',value:'EXPENSE'},{label:'收入',value:'INCOME'}]}/><TextInput leftSection={<Search size={15}/>} placeholder="搜索商户或备注" value={keyword} onChange={e=>setKeyword(e.target.value)}/></Group><Divider my="lg"/><ScrollArea><Table miw={760} verticalSpacing="md" highlightOnHover><Table.Thead><Table.Tr><Table.Th>日期</Table.Th><Table.Th>交易对象</Table.Th><Table.Th>分类</Table.Th><Table.Th>账户</Table.Th><Table.Th>备注</Table.Th><Table.Th ta="right">金额</Table.Th><Table.Th w={44}/></Table.Tr></Table.Thead><Table.Tbody>{filtered.map(t=><Table.Tr key={t.id}><Table.Td><Text size="xs" c="dimmed">{t.transactionDate}</Text></Table.Td><Table.Td><Text fw={600} size="sm">{t.merchant}</Text></Table.Td><Table.Td><Badge variant="light" style={{color:t.categoryColor,background:`${t.categoryColor}18`}}>{t.categoryName}</Badge></Table.Td><Table.Td><Text size="xs">{t.accountName}</Text></Table.Td><Table.Td><Text size="xs" c="dimmed">{t.note||'—'}</Text></Table.Td><Table.Td ta="right"><Text fw={700} c={t.type==='INCOME'?'teal':'red'}>{t.type==='INCOME'?'+':'−'} {money(t.amount)}</Text></Table.Td><Table.Td><Tooltip label="删除"><ActionIcon variant="subtle" color="gray" onClick={()=>remove(t.id)}><Trash2 size={15}/></ActionIcon></Tooltip></Table.Td></Table.Tr>)}</Table.Tbody></Table></ScrollArea>{!filtered.length&&<Center py={60}><Text c="dimmed" size="sm">没有符合条件的账目</Text></Center>}</Paper></div>;
}
function TransactionTable({data}){return <ScrollArea><Table miw={680} verticalSpacing="md" highlightOnHover><Table.Thead><Table.Tr><Table.Th>日期</Table.Th><Table.Th>交易对象</Table.Th><Table.Th>分类</Table.Th><Table.Th>账户</Table.Th><Table.Th ta="right">金额</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{data.map(t=><Table.Tr key={t.id}><Table.Td><Text size="xs" c="dimmed">{t.transactionDate}</Text></Table.Td><Table.Td><Text fw={600} size="sm">{t.merchant}</Text></Table.Td><Table.Td><Badge variant="light" style={{color:t.categoryColor,background:`${t.categoryColor}18`}}>{t.categoryName}</Badge></Table.Td><Table.Td><Text size="xs">{t.accountName}</Text></Table.Td><Table.Td ta="right"><Text fw={700} c={t.type==='INCOME'?'teal':'red'}>{t.type==='INCOME'?'+':'−'} {money(t.amount)}</Text></Table.Td></Table.Tr>)}</Table.Tbody></Table></ScrollArea>}

function RecordModal({opened,onClose,accounts,categories,onSaved}){
  const [type,setType]=useState('EXPENSE'),[amount,setAmount]=useState(''),[categoryId,setCategoryId]=useState(null),[accountId,setAccountId]=useState(null),[merchant,setMerchant]=useState(''),[note,setNote]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[saving,setSaving]=useState(false);
  const available=categories.filter(x=>x.type===type);
  useEffect(()=>{setCategoryId(available[0]?.id||null)},[type,categories]);
  useEffect(()=>{if(!accountId&&accounts[0])setAccountId(accounts[0].id)},[accounts,accountId]);
  const save=async()=>{if(!amount||!categoryId||!accountId||!merchant){notifications.show({color:'yellow',message:'请填写金额、分类、账户和交易对象'});return}setSaving(true);try{await api.createTransaction({type,amount:Number(amount),categoryId:Number(categoryId),accountId:Number(accountId),transactionDate:date,merchant,note});notifications.show({color:'teal',title:'已记账',message:`${type==='INCOME'?'收入':'支出'} ${money(amount)}`});setAmount('');setMerchant('');setNote('');await onSaved()}catch(e){notifications.show({color:'red',message:e.message})}finally{setSaving(false)}};
  return <Modal opened={opened} onClose={onClose} centered radius="xl" title={<Text fw={800}>记一笔</Text>} size="md"><Stack gap="lg"><SegmentedControl fullWidth value={type} onChange={setType} data={[{label:'支出',value:'EXPENSE'},{label:'收入',value:'INCOME'}]}/><NumberInput label="金额" placeholder="0.00" prefix="¥ " value={amount} onChange={setAmount} decimalScale={2} size="lg" min={0}/><div><Text size="sm" fw={500} mb={8}>分类</Text><div className="category-picker">{available.map(c=>{const Icon=iconMap[c.icon]||Shapes;return <button className={String(categoryId)===String(c.id)?'selected':''} key={c.id} onClick={()=>setCategoryId(c.id)}><ThemeIcon variant="light" radius="xl" style={{color:c.color,background:`${c.color}18`}}><Icon size={17}/></ThemeIcon><span>{c.name}</span></button>})}</div></div><SimpleGrid cols={2}><Select label="资金账户" value={accountId} onChange={setAccountId} data={accounts.map(a=>({value:a.id,label:`${a.name} · ${money(a.balance)}`}))}/><TextInput label="交易日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/></SimpleGrid><TextInput label={type==='INCOME'?'收入来源':'交易对象'} placeholder={type==='INCOME'?'例如：工资收入':'例如：盒马鲜生'} value={merchant} onChange={e=>setMerchant(e.target.value)}/><TextInput label="备注（选填）" placeholder="补充一点说明" value={note} onChange={e=>setNote(e.target.value)}/><Button size="md" loading={saving} onClick={save}>保存这笔{type==='INCOME'?'收入':'支出'}</Button></Stack></Modal>;
}

function CategoriesPage({data,onRefresh}){
  const [type,setType]=useState('EXPENSE'),[opened,modal]=useDisclosure(false),[name,setName]=useState(''),[color,setColor]=useState('#3154E5');const items=data.filter(x=>x.type===type);
  const save=async()=>{try{await api.saveCategory({name,type,icon:type==='INCOME'?'CirclePlus':'Shapes',color});notifications.show({color:'teal',message:'自定义分类已添加'});setName('');modal.close();await onRefresh()}catch(e){notifications.show({color:'red',message:e.message})}};
  return <div className="page-in"><PageHead kicker="CATEGORIES" title="收支分类" text="常用分类已经准备好，也可以按自己的习惯添加。" action={<Button leftSection={<Plus size={16}/>} onClick={modal.open}>添加分类</Button>}/><SegmentedControl value={type} onChange={setType} data={[{label:`支出分类 ${data.filter(x=>x.type==='EXPENSE').length}`,value:'EXPENSE'},{label:`收入分类 ${data.filter(x=>x.type==='INCOME').length}`,value:'INCOME'}]}/><SimpleGrid cols={{base:2,sm:3,lg:4}} mt="lg" spacing="lg">{items.map(c=>{const Icon=iconMap[c.icon]||Shapes;return <Paper className="category-item" p="lg" radius="xl" key={c.id}><Group justify="space-between"><ThemeIcon size={44} radius="xl" variant="light" style={{color:c.color,background:`${c.color}18`}}><Icon size={20}/></ThemeIcon>{c.systemCategory?<Badge size="xs" color="gray" variant="light">系统</Badge>:<ActionIcon variant="subtle" color="gray"><Pencil size={15}/></ActionIcon>}</Group><Text fw={700} mt="lg">{c.name}</Text><Text size="xs" c="dimmed" mt={3}>{type==='INCOME'?'日常收入':'日常支出'}</Text></Paper>})}</SimpleGrid><Modal opened={opened} onClose={modal.close} title={<Text fw={700}>添加自定义分类</Text>} centered radius="xl"><Stack><SegmentedControl fullWidth value={type} onChange={setType} data={[{label:'支出',value:'EXPENSE'},{label:'收入',value:'INCOME'}]}/><TextInput label="分类名称" placeholder="例如：宠物" value={name} onChange={e=>setName(e.target.value)}/><TextInput label="标识颜色" value={color} onChange={e=>setColor(e.target.value)} leftSection={<ColorSwatch color={color} size={16}/>}/><Button onClick={save}>保存分类</Button></Stack></Modal></div>;
}

function AccountsPage({data,onRefresh}){
  const [opened,modal]=useDisclosure(false),[edit,setEdit]=useState(null),[form,setForm]=useState({name:'',type:'储蓄卡',balance:0,color:'#3154E5'});
  const begin=a=>{setEdit(a||null);setForm(a?{name:a.name,type:a.type,balance:Number(a.balance),color:a.color}:{name:'',type:'储蓄卡',balance:0,color:'#3154E5'});modal.open()};
  const save=async()=>{try{await api.saveAccount(form,edit?.id);notifications.show({color:'teal',message:edit?'账户余额已校正':'账户已添加'});modal.close();await onRefresh()}catch(e){notifications.show({color:'red',message:e.message})}};
  return <div className="page-in"><PageHead kicker="ACCOUNTS" title="资金账户" text="管理银行卡、微信、支付宝和现金余额。" action={<Button leftSection={<Plus size={16}/>} onClick={()=>begin()}>添加账户</Button>}/><SimpleGrid cols={{base:1,sm:2,lg:3}} spacing="lg">{data.map(a=>{const Icon=a.type==='电子钱包'?Smartphone:a.type==='信用卡'?CreditCard:Building2;return <Card className="account-item" p="xl" radius="xl" key={a.id}><Group justify="space-between"><ThemeIcon size={44} radius="lg" style={{background:a.color}}><Icon size={20}/></ThemeIcon><ActionIcon variant="subtle" color="gray"><MoreHorizontal size={17}/></ActionIcon></Group><Text size="xs" c="dimmed" mt="xl">{a.type}</Text><Text fw={700} mt={3}>{a.name}</Text><Title order={3} mt="lg">{money(a.balance)}</Title><Group mt="xl" justify="space-between"><Text size="xs" c="dimmed">初始 {money(a.initialBalance)}</Text><Button size="xs" variant="light" onClick={()=>begin(a)}>校正余额</Button></Group></Card>})}<button className="add-account" onClick={()=>begin()}><ThemeIcon variant="light" radius="xl"><Plus size={18}/></ThemeIcon><Text fw={700} size="sm">添加账户</Text><Text size="xs" c="dimmed">首次可设置初始金额</Text></button></SimpleGrid><Modal opened={opened} onClose={modal.close} title={<Text fw={700}>{edit?'校正账户':'添加账户'}</Text>} centered radius="xl"><Stack><TextInput label="账户名称" placeholder="例如：工商银行" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="账户类型" value={form.type} onChange={v=>setForm({...form,type:v})} data={['储蓄卡','工资卡','电子钱包','信用卡','现金']}/><NumberInput label={edit?'校正后余额':'初始金额'} prefix="¥ " value={form.balance} onChange={v=>setForm({...form,balance:Number(v)})} decimalScale={2}/><TextInput label="标识颜色" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/><Button onClick={save}>保存账户</Button></Stack></Modal></div>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
